name: Terraform Plan

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  tf_actions_working_dir: ./challenge1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION}}
  environment: dev

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: ${environment}
    
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Select Workspace
      id: select-workspace
      run: terraform workspace select ${environment} || terraform workspace new ${environment}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color
      continue-on-error: false